INCREMENT_TYPE_FIXED = "fixed"
INCREMENT_TYPE_VARIABLE = "variable"

B_PRICE = 10
R_PRICE = 5
ST_PRICE = 2.5

B = 'b'
R = 'r'
ST = 'st'

DEFAULT_QUANTITY = 0
DEFAULT_INCREMENT = 0
DEFAULT_INCREMENT_TYPE = "fixed"

LOGGER_FILE_LOC = ".//logs//app.log"
TEST_WRONG_INPUT = "false"
